### ISSUE TITLE
Add in solving linear problems to the document to demonstrate the use

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/SimpleDifferentialOperators.jl#20]
Main
- [x] On the README, this means doing something with the returned `A`...  (Resolved in #27)
- [x] Currently we have a bunch of matrices `A`, but I think we should reserve that for affine ones.   Use `L` (Resolved in #27)
- [x] Move the "Formulas" in https://quantecon.github.io/SimpleDifferentialOperators.jl/latest/ to a different page so it doesn't clutter the usage (Resolved in 19e613e)
- [x] In the "Usage" make sure that you add in the new interior one in #18 and the new x_bar from #19 (Resolved in 7f2ba76) 

Docs on methods
- [x] Try to make the docstring (displayed automatically here) more standard, including built-in example/etc.  See https://juliadocs.github.io/Documenter.jl/latest/man/examples/ for some examples.  Having a `doctest` isn't the worst idea. (Resolved in 5091450)
- [x] Add in more examples to the https://quantecon.github.io/SimpleDifferentialOperators.jl/  .  For example, maybe some variation of #18  where we will also show an example with the LCP later. (Resolved in 5091450)
